language: java
jdk:
  - oraclejdk8
  - oraclejdk9

before_install:
  - wget https://services.gradle.org/distributions/gradle-4.6-bin.zip
  - unzip gradle-4.6-bin.zip
  - export GRADLE_HOME=$PWD/gradle-4.6
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -b wrapper.gradle wrapper

before_script:
  - gradle wrapper
  - chmod +x gradlew
script:
  - ./gradlew check
  - ./gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
