language: java
jdk:
  - oraclejdk8
  - oraclejdk9

before_install:
  - gradle -b wrapper.gradle wrapper

before_script:
  - gradle wrapper
  - chmod +x gradlew
script:
  - ./gradlew check
  - ./gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
